import type { Metadata } from 'next';
import './globals.css';

//font
import { montserrat, comfortana } from '@/lib/fonts';
// layout
import NavBar from '@/components/ui/layout/navbar/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${comfortana.variable}`}>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
